name: Generate Datas

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - uses: Sutil/snk@blue-snake
        id: snake-gif
        with:
          github_user_name: Sutil
          svg_out_path: dist/github-contribution-grid-snake2.svg
          l1: '#6229e6'
          l2: '#8257e6'
          l3: '#a187de'
          l4: '#c3b8de'
          empty_color: 'rgba(10,10,10,0.05)'
          snake_color: '#04d361'

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
